# telstra_messaging_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # The base Uri for API calls
    @base_uri = 'https://tapi.telstra.com/v2'

    # OAuth 2 Client ID
    @o_auth_client_id = 'TODO: Replace'

    # OAuth 2 Client Secret
    @o_auth_client_secret = 'TODO: Replace'

    # Object for storing information about the OAuth token
    @o_auth_token = nil

    # Callback (Proc) to be called when OAuth token is acquired or refreshed
    @o_auth_callback = nil

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :base_uri
      attr_accessor :o_auth_client_id
      attr_accessor :o_auth_client_secret
      attr_accessor :o_auth_token
      attr_accessor :o_auth_callback
    end
  end
end
