# telstra_messaging_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # DeleteNumberRequest Model.
  class DeleteNumberRequest < BaseModel
    # Empty Arr
    # @return [Integer]
    attr_accessor :empty_arr

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['empty_arr'] = 'emptyArr'
      @_hash
    end

    def initialize(empty_arr = 0)
      @empty_arr = empty_arr
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      empty_arr = hash['emptyArr'] ||= 0

      # Create object from extracted values.
      DeleteNumberRequest.new(empty_arr)
    end
  end
end
