# telstra_messaging_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # OAuthResponse Model.
  class OAuthResponse < BaseModel
    # OAuth access token
    # @return [String]
    attr_accessor :access_token

    # OAuth token type
    # @return [String]
    attr_accessor :token_type

    # OAuth expiry time
    # @return [String]
    attr_accessor :expires_in

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['access_token'] = 'access_token'
      @_hash['token_type'] = 'token_type'
      @_hash['expires_in'] = 'expires_in'
      @_hash
    end

    def initialize(access_token = nil,
                   token_type = nil,
                   expires_in = nil)
      @access_token = access_token
      @token_type = token_type
      @expires_in = expires_in
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      access_token = hash['access_token']
      token_type = hash['token_type']
      expires_in = hash['expires_in']

      # Create object from extracted values.
      OAuthResponse.new(access_token,
                        token_type,
                        expires_in)
    end
  end
end
