# telstra_messaging_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # ProvisionNumberResponse Model.
  class ProvisionNumberResponse < BaseModel
    # The mobile phone number that was allocated
    # @return [String]
    attr_accessor :destination_address

    # Metadata for provisioned numbers which are valid for more than 5 years
    # @return [String]
    attr_accessor :description

    # Free Trial apps will have a 30-Day Limit for their provisioned number.
    # This is in Unix time format.
    # @return [Float]
    attr_accessor :expiry_date

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['destination_address'] = 'destinationAddress'
      @_hash['description'] = 'description'
      @_hash['expiry_date'] = 'expiryDate'
      @_hash
    end

    def initialize(destination_address = nil,
                   description = nil,
                   expiry_date = nil)
      @destination_address = destination_address
      @description = description
      @expiry_date = expiry_date
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      destination_address = hash['destinationAddress']
      description = hash['description']
      expiry_date = hash['expiryDate']

      # Create object from extracted values.
      ProvisionNumberResponse.new(destination_address,
                                  description,
                                  expiry_date)
    end
  end
end
