# telstra_messaging_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # ProvisionNumberRequest Model.
  class ProvisionNumberRequest < BaseModel
    # The number of days before for which this number is provisioned.
    # @return [Integer]
    attr_accessor :active_days

    # A notification URL that will be POSTed to whenever a new message (e.g. a
    # reply to a message sent) arrives at this destination address. 
    # If this is not provided then you can use the Get /sms or /mms API to poll
    # for reply messages.
    # *Please note that the notification URLs and the Get /sms or /mms call are
    # exclusive. If a notification URL has been set then the GET call will not
    # provide any useful information.*
    # @return [String]
    attr_accessor :notify_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['active_days'] = 'activeDays'
      @_hash['notify_url'] = 'notifyURL'
      @_hash
    end

    def initialize(active_days = 30 days,
                   notify_url = nil)
      @active_days = active_days
      @notify_url = notify_url
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      active_days = hash['activeDays'] ||= 30 days
      notify_url = hash['notifyURL']

      # Create object from extracted values.
      ProvisionNumberRequest.new(active_days,
                                 notify_url)
    end
  end
end
